configuration:
  - Release
before_build:
  - nuget restore
after_test:
  - ps: .\build\nuget\pack.ps1
  - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
deploy:
  - provider: NuGet
    api_key:
      secure: 9ebswdLv/QpQcZHHGZI6pJKSQu6tU+iSMKkRxd+2FkzcGW7byqkkm29Z80Ys4Fat
    skip_symbols: false
    artifact: /.*\.nupkg/
